#NewClock Settings
#Mon Jun 22 12:41:56 CEST 2026
clock.0.bgtransparency=50
clock.0.color=255,120,70
clock.0.monitor=0
clock.0.position=TopRight
clock.0.seconds=true
clock.0.textSize=10
clock.0.timeshift=0
clock.count=1
